name: Deploy Vite site

on:
  push:
    branches: [ main ]
  workflow_dispatch: # allows manual prod deploys

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: dist

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Vite site
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  staging:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: staging
    steps:
      - name: Deploy to GitHub Pages (staging)
        id: deployment
        uses: actions/deploy-pages@v4

  production:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
    steps:
      - name: Deploy to GitHub Pages (production)
        id: deployment
        uses: actions/deploy-pages@v4
